Put in port forwards to connect to tools

diff --git a/anubis-setup b/anubis-setup
--- a/anubis-setup
+++ b/anubis-setup
@@ -193,7 +193,9 @@ This is the administrative command-line tool for the Anubis system
                 --list-configmaps        : shows a listing of the current configuration maps
                 --show-configmap <configmap name> : shows the configuration associated with the supplied configuration name (default: outputs-infrastructure)
                 --query-logs             : creates connection to log search index and brings up front end in browser
-                --query-metrics          : creates connection to metrics index and rings up front end in browser
+                --query-metrics          : creates connection to metrics index (and brings up front end in browser interface)
+                --query-graphs           : creates connection to dashboard server (and brings up front end browser interface)
+                --query-alerts           : creates connection to alert manager (and brings up front end interface)
                 --snoop-events <topic name(s)> : streams event log to terminal
       ====>>    -- | --driver            : consumes ALL subsequent args and dispatches them to Anubis \"driver\" sub command (see help below)
                 --help                   : (this output)
@@ -206,6 +208,11 @@ This is the administrative command-line tool for the Anubis system
 
     (cd ${ANUBIS_REPO_HOME}/ci; AWS_PROFILE=${AWS_PROFILE} ./anubis-driver.py --help)
     exit 0
+}
+
+sanity_check(){
+    ((DEBUG)) && echo "Calling \"sanity_check\"..."
+    #TODO call checklist heree
 }
 
 list_profiles(){
@@ -235,7 +242,6 @@ as() {
     fi
 }
 
-#TODO
 sync_config_to_profile() {
     ((DEBUG)) && echo "Calling \"sync_config_to_profile\" function with: $@"
     echo "Current profile: ${AWS_PROFILE}"
@@ -319,11 +325,42 @@ query_logs() {
     open http://localhost:9200/_plugin/kibana
 }
 
-#TODO
 # To connect to Prometheus' query front end, PromDash
 query_metrics() {
     ((DEBUG)) && echo "Calling \"query_metrics\" function with: $@"
+    local kubeconfig_file="${ANUBIS_REPO_HOME}/baictl/drivers/aws/cluster/.terraform/bai/kubeconfig"
+    if [[ ! -f "${kubeconfig_file}" ]]; then
+        printf "\033[01;31m[WARNING]\033[0m CANNOT FIND THE REQUIRED CONFIGURATION FILE!\n\n" >&2
+        ((!DEBUG)) && exit 1
+    fi
+    ("${ANUBIS_REPO_HOME}"/baictl/baictl port-forward infra --service="prometheus" &&\
+         open http://localhost:9090)
 }
+
+# To connect to Grafana dashboard
+query_graphs() {
+    ((DEBUG)) && echo "Calling \"query_graphs\" function with: $@"
+    local kubeconfig_file="${ANUBIS_REPO_HOME}/baictl/drivers/aws/cluster/.terraform/bai/kubeconfig"
+    if [[ ! -f "${kubeconfig_file}" ]]; then
+        printf "\033[01;31m[WARNING]\033[0m CANNOT FIND THE REQUIRED CONFIGURATION FILE!\n\n" >&2
+        ((!DEBUG)) && exit 1
+    fi
+    ("${ANUBIS_REPO_HOME}"/baictl/baictl port-forward infra --service="grafana" &&\
+         open http://127.0.0.1:3000)
+}
+
+# To connect to Alert Manager dashboard
+query_alerts() {
+    ((DEBUG)) && echo "Calling \"query_alerts\" function with: $@"
+    local kubeconfig_file="${ANUBIS_REPO_HOME}/baictl/drivers/aws/cluster/.terraform/bai/kubeconfig"
+    if [[ ! -f "${kubeconfig_file}" ]]; then
+        printf "\033[01;31m[WARNING]\033[0m CANNOT FIND THE REQUIRED CONFIGURATION FILE!\n\n" >&2
+        ((!DEBUG)) && exit 1
+    fi
+    ("${ANUBIS_REPO_HOME}"/baictl/baictl port-forward infra --service="alertmanager" &&\
+         open http://localhost:9093)
+}
+
 
 #TODO
 # To connect *through* the bastion host to the listen directly to specified topic on Kaffka
@@ -341,6 +378,10 @@ main() {
         case "${1}" in
             --force | -f)
                 FORCE=1
+                ;;
+            --check| --sanity-check)
+                sanity_check
+                exit $?
                 ;;
             --list-profiles)
                 list_profiles
@@ -374,6 +415,14 @@ main() {
             --query-metrics) #PromDash access (play with Prometheus queries)
                 shift
                 query_metrics "${1}"
+                ;;
+            --query-graphs) #PromDash access (play with Prometheus queries)
+                shift
+                query_graphs "${1}"
+                ;;
+            --query-alerts) #PromDash access (play with Prometheus queries)
+                shift
+                query_alerts "${1}"
                 ;;
             --snoop-events) #Kubectl logs (Kubernetes logs)
                 shift
