check subshell exit code

diff --git a/baictl/drivers/aws/baidriver b/baictl/drivers/aws/baidriver
--- a/baictl/drivers/aws/baidriver
+++ b/baictl/drivers/aws/baidriver
@@ -252,6 +252,8 @@ _add_extra_users_roles(){
             export KUBECONFIG=${kubeconfig}
             python3 ${src_dir}/add_permission_to_aws_auth_configmap.py --iam-user-arn $user --iam-user-username $(echo $user | sed -n 's/.*\/\(.[a-zA-Z0-9]*\)/\1/p') --iam-user-groups system:masters || return 1
         )
+        local exit_code=$?
+        [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
     done
 
     for role in $(echo $extra_roles | sed "s/,/ /g")
@@ -260,6 +262,8 @@ _add_extra_users_roles(){
             export KUBECONFIG=${kubeconfig}
             python3 ${src_dir}/add_permission_to_aws_auth_configmap.py --role-arn $ --role-username $(echo $role | sed -n 's/.*\/\(.[a-zA-Z0-9]*\)/\1/p') --role-groups system:masters || return 1
         )
+        local exit_code=$?
+        [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
     done
 }
 
