Fix lacking re-creation of kubeflow setup (#475)
* Fix lacking re-creation of kubeflow setup
Add error check

* Add check of correct kubeflow server

* Add subshell

diff --git a/baictl/drivers/aws/baidriver b/baictl/drivers/aws/baidriver
--- a/baictl/drivers/aws/baidriver
+++ b/baictl/drivers/aws/baidriver
@@ -245,42 +245,60 @@ EOF
 }
 
 _install_kubeflow_operators() {
-    if [[ ! -d "$data_dir/kubeflow-ks-app" ]]; then
     (
-        mkdir $data_dir/kubeflow-ks-app
-        cd $data_dir/kubeflow-ks-app
+    _check_kubeflow_app_config
 
-        export KUBECONFIG=$kubeconfig
-        ks init ks_app
+    mkdir $data_dir/kubeflow-ks-app
+    cd $data_dir/kubeflow-ks-app
 
-        cd ks_app || return 1
-
-        echo "-> Creating kubeflow namespace"
-        __create_kubeflow_namespace | ${kubectl} apply -f -
-
-        echo "-> Applying kubeflow stuff"
-        ks registry add kubeflow https://github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow && \
-            ks env add kubeflow --namespace "$kubeflow_namespace" && \
-            ks pkg install kubeflow/mpi-job && \
-            ks pkg install kubeflow/mxnet-job && \
-            ks generate mpi-operator mpi-operator && \
-            ks generate mxnet-operator mxnet-operator
-        local exit_code=$?
-        [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
-    )
-    fi
-
-    echo "-> Kubeflow should be already installed, re-applying configuration"
-    (
     export KUBECONFIG=$kubeconfig
-    cd $data_dir/kubeflow-ks-app/ks_app
+    ks init ks_app || echo "App already exists, continuing" # If the creation fails, the following cd will fail
+
+    cd ks_app || return 1
+
+    echo "-> Creating kubeflow namespace"
+    __create_kubeflow_namespace | ${kubectl} apply -f - || return 1
+
+    echo "-> Creating kubeflow environment"
+    ks registry describe kubeflow || ks registry add kubeflow https://github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow || return 1
+    ks env describe "$kubeflow_namespace" || ks env add kubeflow --namespace "$kubeflow_namespace" || return 1
+
+    echo "-> Applying kubeflow stuff"
+    ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mpi-job" || ks pkg install kubeflow/mpi-job || return 1 && \
+        ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mxnet-job" || ks pkg install kubeflow/mxnet-job || return 1 && \
+        ks component list | awk '{print $1}' | xargs | grep "mpi-operator" || ks generate mpi-operator mpi-operator || return 1 && \
+        ks component list | awk '{print $1}' | xargs | grep "mxnet-operator" || ks generate mxnet-operator mxnet-operator || return 1
+
+
     ks apply kubeflow --component mpi-operator && \
         ks apply kubeflow --component mxnet-operator
+    )
     local exit_code=$?
     [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
-    )
 
     return 0
+}
+
+_check_kubeflow_app_config() {
+    local kubeflow_config_path="${data_dir}/kubeflow-ks-app/ks_app/app.yaml"
+    if [[ ! -f ${kubeflow_config_path} ]]; then
+        echo "Kubeflow is not initialized yet"
+        # Just to be safe
+        rm -rf $data_dir/kubeflow-ks-app
+        return 0
+    fi
+
+    # Check if URL in config is the right one. if not, it's stale and we have to re-create it
+    local eks_server_url=$(cat $data_dir/kubeconfig | grep -o -e 'https://.*eks.amazonaws.com')
+
+    if grep -q "$eks_server_url" "${kubeflow_config_path}"
+    then
+        echo "Kubeflow already has been connected to the correct EKS server"
+        # code if found
+    else
+        echo "Kubeflow is currently not connected to the correct EKS server"
+        rm -rf $data_dir/kubeflow-ks-app
+    fi
 }
 
 _init_service_account() {
