Fix lacking re-creation of kubeflow setup Add error check

diff --git a/baictl/drivers/aws/baidriver b/baictl/drivers/aws/baidriver
--- a/baictl/drivers/aws/baidriver
+++ b/baictl/drivers/aws/baidriver
@@ -219,32 +219,34 @@ EOF
 }
 
 _install_kubeflow_operators() {
-    if [[ ! -d "$data_dir/kubeflow-ks-app" ]]; then
-    (
-        mkdir $data_dir/kubeflow-ks-app
-        cd $data_dir/kubeflow-ks-app
+    # TODO check /Users/mabreu/.bai/kubeflow-ks-app/ks_app/app.yaml and whether the URL is correct. If not, delete it
 
-        export KUBECONFIG=$kubeconfig
-        ks init ks_app
+    pushd .
+    mkdir $data_dir/kubeflow-ks-app
+    cd $data_dir/kubeflow-ks-app
 
-        cd ks_app || return 1
+    export KUBECONFIG=$kubeconfig
+    ks init ks_app || echo "App already exists, continuing" # If the creation fails, the following cd will fail
 
-        echo "-> Creating kubeflow namespace"
-        __create_kubeflow_namespace | ${kubectl} apply -f -
+    cd ks_app || return 1
 
-        echo "-> Applying kubeflow stuff"
-        ks registry add kubeflow https://github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow && \
-            ks env add kubeflow --namespace "$kubeflow_namespace" && \
-            ks pkg install kubeflow/mpi-job && \
-            ks pkg install kubeflow/mxnet-job && \
-            ks generate mpi-operator mpi-operator && \
-            ks generate mxnet-operator mxnet-operator
-        local exit_code=$?
-        [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
-    )
-    fi
+    echo "-> Creating kubeflow namespace"
+    __create_kubeflow_namespace | ${kubectl} apply -f - || return 1
 
-    echo "-> Kubeflow should be already installed, re-applying configuration"
+    echo "-> Creating kubeflow environment"
+    ks registry describe kubeflow || ks registry add kubeflow https://github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow || return 1
+    ks env describe "$kubeflow_namespace" || ks env add kubeflow --namespace "$kubeflow_namespace" || return 1
+
+    echo "-> Applying kubeflow stuff"
+    ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mpi-job" || ks pkg install kubeflow/mpi-job && \
+        ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mxnet-job" || ks pkg install kubeflow/mxnet-job && \
+        ks component list | awk '{print $1}' | xargs | grep "mpi-operator" || ks generate mpi-operator mpi-operator && \
+        ks component list | awk '{print $1}' | xargs | grep "mxnet-operator" || ks generate mxnet-operator mxnet-operator
+    local exit_code=$?
+    [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
+
+
+    echo "-> Applying configuration"
     (
     export KUBECONFIG=$kubeconfig
     cd $data_dir/kubeflow-ks-app/ks_app
@@ -254,6 +256,7 @@ _install_kubeflow_operators() {
     [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
     )
 
+    popd
     return 0
 }
 
