Removed ksonnet. Using kubeflow mpi-operator instead of.

diff --git a/baictl/drivers/aws/baidriver b/baictl/drivers/aws/baidriver
--- a/baictl/drivers/aws/baidriver
+++ b/baictl/drivers/aws/baidriver
@@ -297,51 +297,26 @@ _add_extra_users_roles(){
         [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
     done
 }
-
-
-__create_kubeflow_namespace(){
-    cat << EOF
-apiVersion: v1
-kind: Namespace
-metadata:
-  name: kubeflow
-EOF
-}
-
 _install_kubeflow_operators() {
     (
     _check_kubeflow_app_config
-
-    mkdir $data_dir/kubeflow-ks-app
-    cd $data_dir/kubeflow-ks-app
-
     export KUBECONFIG=$kubeconfig
-    ks init ks_app || echo "App already exists, continuing" # If the creation fails, the following cd will fail
+    
+    mkdir $data_dir/kubeflow-operators
+    cd $data_dir/kubeflow-operators
 
-    cd ks_app || return 1
+    wget https://raw.githubusercontent.com/kubeflow/mpi-operator/master/deploy/v1alpha2/mpi-operator.yaml
+    kubectl create -f mpi-operator.yaml
 
-    echo "-> Creating kubeflow namespace"
-    __create_kubeflow_namespace | ${kubectl} apply -f - || return 1
-
-    echo "-> Creating kubeflow environment"
-    ks registry describe kubeflow || ks registry add kubeflow https://github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow || return 1
-    ks env describe "$kubeflow_namespace" || ks env add kubeflow --namespace "$kubeflow_namespace" || return 1
-
-    echo "-> Applying kubeflow stuff"
-    ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mpi-job" || ks pkg install kubeflow/mpi-job || return 1 && \
-        ks pkg list --installed -o table | awk '{print $2}' | xargs | grep "mxnet-job" || ks pkg install kubeflow/mxnet-job || return 1 && \
-        ks component list | awk '{print $1}' | xargs | grep "mpi-operator" || ks generate mpi-operator mpi-operator || return 1 && \
-        ks component list | awk '{print $1}' | xargs | grep "mxnet-operator" || ks generate mxnet-operator mxnet-operator || return 1
-
-    # Enforce mpi-operator version 0.2.0
-    ks param set mpi-operator image mpioperator/mpi-operator:0.2.0
-
-    ks apply kubeflow --component mpi-operator && \
-        ks apply kubeflow --component mxnet-operator
+    git clone https://github.com/kubeflow/mxnet-operator.git
+    kubectl create -k mxnet-operator/manifests/overlays/v1beta1/    
     )
-    local exit_code=$?
-    [[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
 
+    local exit_code=$?
+    #kubectl create returns 1 in case operators are already exists
+    #TODO: add a handler
+    #[[ "$exit_code" != 0 ]] && echo "[ERROR] Failed with exit code: $exit_code" && return 1
+   
     return 0
 }
 
