add smart-watcher feature

diff --git a/bai-bff/bin/anubis b/bai-bff/bin/anubis
--- a/bai-bff/bin/anubis
+++ b/bai-bff/bin/anubis
@@ -161,6 +161,7 @@ This is the command-line, client-side interface to the Bechmark AI service...
           --show-registered-service-endpoint : The hostname|IP:PORT of anubis service you are using
           --show-registered-service-endpoint-history : listing of endpoints you have previously registered
           --version                : shows version
+          --get-client-id          : shows client-id
           --legend                 : displays quick legend of the emojis used
           --help                   : (this output)
 
@@ -230,7 +231,11 @@ _construct_endpoint_URL() {
 }
 
 get_client_id() {
-    echo -n "$(printf "$(whoami)+$(hostname)" | sha1sum | awk '{print $1}')"
+    if [[ -z "${CLIENT_ID}" ]]; then
+      echo -n "$(printf "$(whoami)+$(hostname)" | sha1sum | awk '{print $1}')"
+    else
+      echo "${CLIENT_ID}"
+    fi
 }
 
 service_version_check() {
@@ -571,11 +576,17 @@ _read_local_submission_status() {
     current_action_id=$action_id
 
     local datafile=${ANUBIS_DATABASE}/$(get_client_id)"/"${action_id}/data
-
     if [[ -f "${datafile}" ]]; then
         jq --compact-output '{src: .visited[-1].svc , id: .message_id, msg: .payload.message, tstamp: .visited[-1].tstamp}' "${datafile}" | while read line; do _as_status_line $line; done;
     else
         ((VERBOSE)) && printf "Events datafile [%s] is not present\n" "${datafile}"
+        return 1
+    fi
+    failed=$(jq --compact-output '{src: .visited[-1].svc , id: .message_id, msg: .payload.message, tstamp: .visited[-1].tstamp}' "${datafile}"  | grep "failed")
+    if [[ -n "${failed}" ]]; then
+      exit 1
+    else
+      exit 0
     fi
 }
 
@@ -583,22 +594,22 @@ _read_remote_submission_status() {
     local action_id=${1:-$(use_last_action_id)}
     ((DEBUG)) && echo "_read_remote_submission_status for action: ${action_id}" 1>&2
     current_action_id=$action_id
-
     local path=$(get_client_id)"/"${action_id}
     local current_service_endpoint=$(_get_current_service_endpoint)
     local cmd
-
     ((VERBOSE)) && echo "database = ${ANUBIS_DATABASE}"
-
     local since_tstamp=$(get_latest_event_timestamp "${action_id}")
-
     cmd="curl -s -D >(service_version_check) -X GET -G -H Content-Type: application/json --data-urlencode since="${since_tstamp}" http://"${current_service_endpoint}"/api/job/"${path}
     ((VERBOSE)) && echo ${cmd}
     local response=$(eval ${cmd})
-
     if [[ -n "${response}" ]]; then
         [[ ! -d "${ANUBIS_DATABASE}/${path}" ]] && mkdir -p "${ANUBIS_DATABASE}/${path}"
         echo "${response}" | jq '.[]' | tee $( [[ ${since_tstamp} != "0" ]] && echo -n "-a") ${ANUBIS_DATABASE}/${path}/data 2> /dev/null | jq --compact-output '{src: .visited[-1].svc , id: .message_id, msg: .payload.message, tstamp: .visited[-1].tstamp} +{"new" : "1"}' | while read line; do _as_status_line $line; done;
+    fi
+    if [[ -z "${response}" ]]; then
+      echo 5
+    else
+      echo 0
     fi
 }
 
@@ -614,6 +625,8 @@ _looks_like_an_action_id() {
 #REST API call
 get_submission_status() {
     local action_id=${1:-$(use_last_action_id)}
+    local timeout_counter=0
+    local remote_status=0
     ((DEBUG)) && echo "[DEBUG] - get_submission_status, was passed in [${action_id}]" 1>&2
     if ! _looks_like_an_action_id "${action_id}" ; then
         printf "\033[01;31m[ERROR] Incorrect action-id format: expecting a UUID\033[0m\n"
@@ -647,13 +660,23 @@ get_submission_status() {
                 fi
             fi
             printf "\033[01;32m.\033[0m"
-            _read_remote_submission_status "${action_id}"
+            remote_status=$(_read_remote_submission_status "${action_id}")
+            timeout_counter=$((timeout_counter+remote_status))
+            if [[ remote_status -eq 0 ]]; then
+              timeout_counter=0
+            elif [[ timeout_counter -eq 30 ]]; then
+              printf "\033[01;31m[no connection to service... checking local logs]\033[0m\n"
+              _read_local_submission_status
+              printf "\033[01;31m[no local logs.... error]\033[0m\n"
+              exit 1
+            fi
             sleep "${WATCH_PERIOD}"
+
         done
     else
         curl -s "$(_construct_endpoint_URL)"/ready >& /dev/null
         if (( $? != 0 )); then
-            printf "\033[01;31m[no connection to service]\033[0m\n"
+            printf "\n\033[01;31m[No connection/timedout... check for local submission file]\033[0m\n"
             exit 9
         fi
         _read_remote_submission_status "${action_id}"
@@ -907,6 +930,10 @@ main() {
                     ;;
                 --ping-service-endpoint | --ping)
                     ping_service_endpoint
+                    exit $?
+                    ;;
+                --get-client-id)
+                    get_client_id
                     exit $?
                     ;;
                 --unregister)
