Now can send cancel event

diff --git a/bff/bin/baictl b/bff/bin/baictl
--- a/bff/bin/baictl
+++ b/bff/bin/baictl
@@ -81,6 +81,10 @@ _construct_endpoint_URL() {
     printf "http://%s" "$(cat "${BAICTL_SERVICE_ENDPOINT_CONFIG}")"
 }
 
+get_client_id() {
+    echo -n "$(sha1sum <<<$(whoami)+$(hostname) | awk '{print $1}')"
+}
+
 ping_service_endpoint() {
     show_registered_service_endpoint && curl -I $(_construct_endpoint_URL)
 }
@@ -113,21 +117,45 @@ check_version() {
     echo "+"; #TODO - make this check against the service's supported version
 }
 
-upgrade() {
-    #TODO - upgrading this tool itself...
-    #TODO - implement how to upgrade to the version supported by the service directly?
-    printf "Sync'ing versions with that of the current service endpoint [\033[01;33m%s\033[0m] \n" "$current_service_endpoint"
-    echo "Implement me!!!!!"
-}
 
-sync_version() {
-    #TODO - implement how to upgrade to the version supported by the service directly?
-    printf "Sync'ing versions with that of the current service endpoint [\033[01;33m%s\033[0m] \n" "$current_service_endpoint"
-    echo "Implement me!!!!!"
+#---------------------------------------------------------
+# Event Construction
+#---------------------------------------------------------
+
+
+_generate_command_event() {
+    local action_id=${1?"generate_command_event() -> You MUST supply the action id as the first argument to this function"}
+    shift
+    local command=${1}
+    shift
+    local command_args=(${@})
+
+    #echo "Number of args is ${#command_args[@]}"
+    local command_args_strings=$(sed 's/.$//g' <<< $(for item in ${command_args[@]}; do echo -n "\""${item}"\","; done))
+    #echo "The args as strings are:${command_args_strings}"
+
+    local event=$(cat <<-EOF
+{
+    "message_id" : "$(uuidgen)",
+    "client_id"  : "$(get_client_id)",
+    "client_version" : "${VERSION}",
+    "client_sha1"    : "${MY_SHA1}",
+    "client_username" : "$(whoami)",
+    "date" : "$(date -u +"%a %b %d %H:%M:%S %Z %Y")",
+    "visited"  : [{"svc" : "${SERVICE_NAME}", "tstamp" : 1557150931877, "version" :"${VERSION}"}],
+    "type" : "CMD_SUBMIT",
+    "payload"  : {
+        "command" : "${command}",
+        "args" : [${command_args_strings}]
+    }
+}
+EOF
+          )
+    jq '.' <<< ${event}
 }
 
 _generate_submit_event() {
-    local descriptor_filename=${1?"generate_submit_event() -> You MUST supply a descriptor file as first argument"}
+    local descriptor_filename=${1?"generate_submit_event() -> You MUST supply a descriptor file as first argument to this function"}
     local event=$(cat <<-EOF
 {
     "message_id" : "$(uuidgen)",
@@ -149,6 +177,21 @@ EOF
           )
     jq '.' <<< ${event}
 }
+#---------------------------------------------------------
+
+upgrade() {
+    #TODO - upgrading this tool itself...
+    #TODO - implement how to upgrade to the version supported by the service directly?
+    printf "Sync'ing versions with that of the current service endpoint [\033[01;33m%s\033[0m] \n" "$current_service_endpoint"
+    echo "Implement me!!!!!"
+}
+
+sync_version() {
+    #TODO - implement how to upgrade to the version supported by the service directly?
+    printf "Sync'ing versions with that of the current service endpoint [\033[01;33m%s\033[0m] \n" "$current_service_endpoint"
+    echo "Implement me!!!!!"
+}
+
 
 submit() {
     local descriptor_filename=${1?"submit() -> You MUST supply a descriptor file as first argument"}
@@ -194,9 +237,26 @@ get_results() {
 
 abort_submission() {
     local action_id=${1:?"abort_submission() -> You MUST provide the action_id returned by the initial submission"}
+    shift
     ((VERBOSE)) && echo "abort submisson ${action_id}"
-    #TODO - implement me
-    echo "(implement me)"
+
+    if [[ -z "${current_service_endpoint}" ]]; then
+        printf "
+\033[01;31m[WARNING]\033[0m You do not have a service endpoint registered.
+          Please do so.  (see --register flag)
+          using localhost, port 8080\n\n";
+        current_service_endpoint="localhost:8080"
+    fi
+
+    local data=$(_generate_command_event ${action_id} "cancel" $*)
+    if [[ -n "${data}" ]]; then
+        cmd="curl -s -X POST -H Content-Type: application/json -d '"${data}"' http://"${current_service_endpoint}"/api/job/$(get_client_id)/${action_id}"
+        ((VERBOSE)) && echo ${cmd}
+        eval ${cmd}
+    else
+        printf '\033[01;31m[ERROR]\033[0m No data to send.\n\n'
+        exit 1
+    fi
 }
 
 
@@ -239,9 +299,10 @@ main() {
                     get_last_action_id
                     exit $?
                     ;;
-                --abort)
+                --abort|--cancel)
                     shift
-                    abort_submission ${1} ; shift
+                    abort_submission ${@} ; shift
+                    exit $?
                     ;;
                 --check-prerequisites) # hidden option
                     shift
